language: node_js
node_js:
  - "18"
dist: focal
script:
  - npm test

deploy:
  provider: pages
  token: $GITHUB_TOKEN  # Reference the GitHub token stored in CI/CD environment variables
  keep_history: true
  local_dir: build
  on:
    branch: main

before_install:
  - nvm install 18
  - nvm use 18
