language: node_js
node_js:
  - "18"
dist: focal
script:
  - npm test
deploy:
  provider: pages
  token: $GITHUB_TOKEN
  edge: true
  skip_cleanup: true
  local_dir: build
  on:
    branch: main
before_install:
  - nvm install 18
