language: node_js
node_js:
  - "18"  # Use a compatible Node.js version like 14, 16, or 18
dist: focal  # This uses Ubuntu 20.04
script:
  - npm test
deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  local_dir: build
  on:
    branch: main
before_install:
  - nvm install 18  # Install Node.js version 18
